name:                wol-hook
version:             0.1.0.0
github:              "gozzarda/wol-hook"
license:             BSD3
author:              "Andrew Gozzard"
maintainer:          "gozzardam@gmail.com"
copyright:           "2019 Andrew Gozzard"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gozzarda/wol-hook#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- wai
- warp
- wol

library:
  source-dirs: src

executables:
  wol-hook:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wol-hook

tests:
  wol-hook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wol-hook
